### ISSUE TITLE
使用Trojan 的情况下多个 HTTPS 域名部署方案 | AGG

### ISSUE THREAD

**Issue by A-GG** [A-GG/a-gg.github.io#2]
https://agg.me/trojan-https-%E5%A4%9A%E5%9F%9F%E5%90%8D%E9%83%A8%E7%BD%B2%E6%96%B9%E6%A1%88/ 

 Enjoy life && Enjoy Coding

**Comment by DingdingLuan** [comment]
好活，有机会试一试

**Comment by A-GG** [comment]
> @DingdingLuan
> 好活，有机会试一试

博客第一个留言，纪念一下。
